### ISSUE TITLE
Support for Oracle Linux?

### ISSUE THREAD

**Issue by jgsuess** [sclorg/devtoolset-container#29]
Oracle Linux has [SCL support](https://docs.oracle.com/cd/E37670_01/E59096/html/ol-scl-pref.html). It would be great to have this container for building stuff on OL. Any chance you could make that a feature?

**Comment by omron93** [comment]
@hhorak @notroj ?

**Comment by hhorak** [comment]
A similar PR is in https://github.com/sclorg/s2i-base-container/pull/111 -- we discussed it already before, that maintaining more copies of Dockerfiles is not easy and we should rather limit the copies we take care of to minimum. Even worse state would be to not update the Dockerfile.

However, since all the derivatives (https://upload.wikimedia.org/wikipedia/commons/a/a3/Redhat_family_tree_11-06.png) would be almost the same as the RHEL one, wouldn't it be enough to change the Dockerfile on the fly during build (FROM field and repo name)?

**Comment by Djelibeybi** [comment]
It should be the same, but our base images are different to the RHEL ones and we don't require any subscription management, so just changing the repo names isn't quite the same.

**Comment by torsava** [comment]
@jgsuess @Djelibeybi Hi! Could I ask what do you see as the advantages of basing the images on Oracle Linux instead of CentOS?

**Comment by jgsuess** [comment]
It allows integrated testing with the UEK, which can behave
 differently from stock kernel, without leaving the container.

Just for disclosure: I work for Oracle Labs, but this is private
interest. I like OL as a platform.

Best, JG

**Comment by torsava** [comment]
@jgsuess Since these requests for more bases are multiplying (centos6, OL, Alpine, ...), we've discussed this issue with the other maintainers and we sadly don't think it's feasible for us to maintain so many variants.

However, if we could help your usecases within the centos based image, please let us know.
